### ISSUE TITLE
Something went wrong while running train.py

### ISSUE THREAD

**Issue by MoLICHENXI** [simonucl/ldgn-mltc#1]
When i run the train.py for 10 epoch, I successfully run the first epoch but went wrong when running the second epoch.
Here, I post the wrong text:

return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: all elements of input should be between 0 and 1

How can i solve this problem?
Thanks very much.
<img width="328" alt="9c834129161ccfd2e400ff9a140c7ba" src="https://user-images.githubusercontent.com/88187261/232540725-5f02f7a6-7711-4b8b-a040-4747125f2c27.png">

**Comment by simonucl** [comment]
Hello @MoLICHENXI , 

I double check and able to reconstruct your error. The main reason is because the learning rate is setting too high and leading a gradient exploding, therefore, I tuned the learning rate from 0.001 to 0.0001 in the latest commits and it works without error after me running 10 epochs so far. Unfortunately the original paper doesn't state any hypereparameter settings, the optimal one may still need more parameter-tuning but at least it works now.

Hope that helps. Please let me know if you still have any errors, otherwise I will treat it as solved.

Best,
Simon

**Comment by MoLICHENXI** [comment]
I get it, thanks for you response.
And there is another question: in the original paper the author said that they use the label embedding but i found that in the code  you just use torch.nn.Parameters(torch.Tensor) as the representation for the label.
So can i use something to replace it ,such as embedding from BERT or Word2vec，Can these operation make the better precision？
I'm looking forward to you reply. Thanks very much

**Comment by simonucl** [comment]
Hello, I think your idea makes sense, as those embedding would bring more contextualized information about the label and should boost the performance of the model. I am looking forward to hearing your outcome after the replacement.

**Comment by MoLICHENXI** [comment]
Thanks for your patient reply，I would like to ask you what else you think the model in this article can be improved.For example，I want to replace some other graph model instead of using GCN. I'm very interested in this work and you code，so i hope I can get some suggestion from you，thanks！

**Comment by simonucl** [comment]
Personally, I think GAT or Graphormer from Microsoft could offer potential improvements on the GNN used. By the way, it seems we share an interest in similar topics. Would you like to connect on social media for more prompt communication? I have Discord, WeChat, etc. Let me know which platform works best for you.

**Comment by MoLICHENXI** [comment]
OK, Thanks for your reply, so how about WeChat？

**Comment by simonucl** [comment]
Sure, you can add me with Wechat ID: simon011130
